(function () {
  const U = n => 'https://commons.wikimedia.org/wiki/Special:FilePath/' + encodeURIComponent(n) + '?width=1600';
  const img = {
    hero: U('During sun rise at digha,west bengal india - panoramio.jpg'),
    about1: U('Fishermen of Bengal 01.jpg'),
    about2: U('Fishing Boat, Rasalpur, East Medinipur.JPG'),
    about3: U('Boat Building, Raswalpur, East Medinipur.JPG'),
    beach: U('Shankarpur beach in Purba Medinipur 03.jpg'),
    n1: U('Fisherman earning time ( hugli river).jpg'),
    n2: U('Shankarpur beach in Purba Medinipur 01.jpg'),
    n3: U('Boat Building1, Raswalpur, East Medinipur.JPG'),
    n4: U('Hilsa (Ilish) fishes for sale at fish market in Domjur, Howrah, West Bengal, India, photographed by Yogabrata Chakraborty, on June 22, 2022.jpg'),
    n5: U('Fish Pond - Tajpur Road - East Midnapore 2015-05-02 9061.JPG'),
  };
  const knots = Array.from({ length: 121 }, (_, i) => i);
  const credit = 'Wikimedia Commons (CC BY-SA)';
  const pad = (a, digits) => a.map((x, i) => Object.assign({ num: digits[i] }, x));
  const enNum = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18'];
  const bnNum = ['০১','০২','০৩','০৪','০৫','০৬','০৭','০৮','০৯','১০','১১','১২','১৩','১৪','১৫','১৬','১৭','১৮'];
  const leaderIds = ['lead-1','lead-2','lead-3','lead-4','lead-5'];
  const newsImg = [img.n1, img.n2, img.n3, img.n4, img.n5];
  const withIds = (items) => items.map((x, i) => Object.assign({ id: leaderIds[i] }, x));
  const withNews = (items) => items.map((x, i) => Object.assign({ id: 'news-' + (i + 1), img: newsImg[i] }, x));

  const en = {
    langCode: 'en', otherLang: 'বাংলা', img, credit, knots,
    nav: { about: 'About', work: 'Our Work', campaigns: 'Campaigns', leadership: 'Leadership', news: 'News', contact: 'Contact', join: 'Join' },
    org: { name: 'Purba Medinipur Matsyajibi Forum', short: 'PMMF', branch: 'A branch of Dakshinbanga Matsyajibi Forum (DMF)', since: 'Since 2018 · Coastal Bengal' },
    hero: { title: 'The sea, the river, and the right to fish.', sub: 'PMMF is a district-level organisation of small-scale and traditional fishworkers. Our members work directly in the fisheries sector, and our purpose is to collectivise fishers, represent them and fight for their rights.', cta1: 'Become a member', cta2: 'Our current demands' },
    stats: [
      { value: '1,208', label: 'Women members' }, { value: '186', label: 'Villages' },
      { value: '15', label: 'Blocks covered' }, { value: '280', label: 'Boats represented' },
      { value: '3', label: 'Sectors: marine, river, inland' }, { value: '2018', label: 'Year founded' },
    ],
    about: {
      kicker: 'About the Forum', title: 'A district forum of fishworkers, run by fishworkers.',
      p1: 'Purba Medinipur has three fishing sectors: marine, riverine and fish-farming. PMMF was formed in 2018 to represent all small-scale and traditional fishworkers in the district, and to address the common challenges they face: ecological decline of waterbodies and fish resources, displacement from fishing grounds, and the loss of livelihoods that follows.',
      p2: 'Our members are fishworkers in the marine, riverine and inland sectors: fishing boat owners, boat crew and boat builders; fish processors, sorters, dryers and vendors, most of whom are women; and, inland, fish-farmers and those who supply fingerlings, harvest fish, prepare feed and maintain ponds.',
      members: ['Boat owners & crew', 'Boat builders', 'Fish processors & dryers', 'Fish vendors', 'Fish-farmers', 'Fingerling suppliers & pond workers'],
    },
    vision: { label: 'Vision', text: 'Small-scale fishers continue to work in the sector with secure livelihoods, control over fish resources, and the ability to protect waterbodies and fish through sustainable practices.' },
    mission: { label: 'Mission', text: 'To build a membership-based organisation with democratic representation and decision-making, and through the mobilisation of our members to place fishers’ demands before the government and achieve their constitutionally guaranteed rights.' },
    networks: { label: 'Networks', items: ['Dakshinbanga Matsyajibi Forum (DMF)', 'National Fishworkers’ Forum (NFF)'] },
    history: { kicker: 'Our journey', title: 'Important moments', items: [
      { year: '2016', title: 'Anti-corruption campaign', text: 'Flagged off a campaign against corruption in a government-sponsored boat-building scheme.' },
      { year: '2018', title: 'Baguran Jalpai beach protected', text: 'Won the fight to restrict vehicles on the beach, curbing tourism pressure; the beach was later declared a Biodiversity Heritage Site.' },
      { year: '2019', title: 'CRZ campaign launched', text: 'Began the Coastal Regulation Zone campaign in response to dilutions of coastal protection laws.' },
      { year: '2021', title: 'Cyclone Yaas', text: 'Fought for livelihood relief and damage compensation in the aftermath of the cyclone.' },
      { year: '2022', title: 'Housing rights won', text: 'Won legal rights for the construction of fishers’ houses on near-coastal stretches.' },
      { year: '2022', title: 'Boat registration for rivers', text: 'Achieved a policy change extending boat registration schemes to the inland riverine sector.' },
      { year: '2023', title: 'Maach ghaats recognised', text: 'Mapped community fish landing centres and secured their inclusion in Department of Fisheries policy.' },
      { year: '2025', title: 'Women’s wing formed', text: 'A dedicated women’s wing of the organisation was formed.' },
      { year: '2025', title: 'Coastal pada-yatra', text: 'Marched along the coast under the banner “Save water, save the coast, save fisherpeople”.' },
      { year: '2026', title: 'Deredighi Canal cleaned', text: 'Cleaned the severely polluted Deredighi Canal in Bhagabanpur-I block.' },
    ] },
    work: { kicker: 'What we work on', title: 'From the boat to the market, and every right in between.', items: pad([
      { title: 'Livelihood rights & fishing grounds', text: 'Protecting traditional fishing grounds and the right to fish in them.' },
      { title: 'Sustainable fisheries', text: 'Advocating a ban on destructive bottom trawling.' },
      { title: 'Against intensive shrimp farming', text: 'Presenting alternative, sustainable fish-farming models.' },
      { title: 'ID cards & schemes', text: 'Fisher identity cards, registration and access to government schemes.' },
      { title: 'Fishing-ban compensation', text: 'Livelihood loss compensation during the annual fishing ban.' },
      { title: 'Cyclone preparedness & relief', text: 'Preparedness, relief and rehabilitation after cyclones.' },
      { title: 'Sea safety', text: 'Safer boats, equipment and rescue for fishers at sea.' },
      { title: 'Social security', text: 'Insurance, pension and welfare schemes for fishworkers.' },
      { title: 'Fishers detained across borders', text: 'Support for fishers detained across maritime borders.' },
      { title: 'CRZ, land & housing', text: 'Coastal regulation, land rights and resisting eviction of fishing settlements.' },
      { title: 'Tourism, ports & industry', text: 'Conflicts with tourism, shipping, dredging, ports and industrial projects.' },
      { title: 'Mangrove & coastal protection', text: 'Protecting mangroves and the coast.' },
      { title: 'Women in fisheries', text: 'Dry fish, processing, marketing and credit for women fishworkers.' },
      { title: 'Fair prices & markets', text: 'Fair pricing, market access and escape from credit indebtedness.' },
      { title: 'Education & health', text: 'Education and health in fishing villages.' },
      { title: 'Legal aid & rights awareness', text: 'Legal support and awareness of fishers’ rights.' },
      { title: 'Training & youth leadership', text: 'Training programmes and building young leaders.' },
      { title: 'Pollution', text: 'Action against industrial effluents, plastic pollution and sewage discharge.' },
    ], enNum) },
    campaigns: { kicker: 'Current campaigns', title: 'What we are demanding today', addressed: 'Addressed to the Department of Fisheries, Government of West Bengal; the District Magistrate, Purba Medinipur; and the Department of Fisheries, Government of India.', items: pad([
      { text: 'Raise fishing-ban compensation and pay it before the ban begins.' },
      { text: 'Strictly enforce the 8 km no-trawling zone reserved for traditional fishers.' },
      { text: 'Issue fisher ID cards to every fishworker, including women dry-fish workers.' },
      { text: 'No eviction of fishing settlements; record customary rights in coastal plans.' },
      { text: 'Rescue boats, radio sets and cyclone shelters at every landing centre.' },
    ], enNum) },
    leaders: { kicker: 'Leadership', title: 'Office bearers', photo: 'Photo', items: withIds([
      { name: 'Amal Bhunia', role: 'President', place: 'Mahishadal Block' },
      { name: 'Srikanta Das', role: 'Vice-President', place: 'Ramnagar-II Block' },
      { name: 'Debasis Shyamal', role: 'Secretary', place: 'Contai-I Block' },
      { name: 'Sahida Bibi', role: 'Assistant Secretary', place: 'Nandigram-I Block' },
      { name: 'Rabindra Nath Bhunia', role: 'Treasurer', place: 'Contai-I Block' },
    ]),
      structureTitle: 'How the Forum is organised', structureText: 'General Body meets once a year · Executive Committee meets monthly · Block units meet every two months · Village samitis meet monthly.',
      womenTitle: 'Women’s wing', womenText: 'A dedicated women’s wing organises dry-fish workers and vendors. One-third of Executive Committee seats are reserved for women.' },
    news: { kicker: 'News & events', title: 'From the coast', upcomingLabel: 'Upcoming', items: withNews([
      { date: '12 Sep 2026', title: 'Deputation to District Magistrate on ban compensation', text: 'Over 300 fishers marched to Tamluk demanding that ban-period relief be released on time.' },
      { date: '28 Aug 2026', title: 'Life jackets distributed at Petuaghat', text: '400 life jackets were handed over to small-boat crews at Petuaghat and Shankarpur.' },
      { date: '5 Aug 2026', title: 'ID card camp in Khejuri-II', text: 'More than 600 fishworkers, a third of them women, applied for fisher ID cards.' },
      { date: '21 Jul 2026', title: 'Women dry-fish workers meet at Junput', text: 'Workers discussed drying-yard space, fair credit and a shared market stall.' },
      { date: '30 Jun 2026', title: 'Mangrove saplings planted along Rasulpur', text: 'Village samitis planted 5,000 saplings and formed guard groups.' },
    ]), upcoming: [
      { date: '18 Oct 2026', text: 'Block-level convention, Ramnagar-II' },
      { date: '21 Nov 2026', text: 'World Fisheries Day rally, Contai' },
      { date: 'Dec 2026', text: 'Annual General Body meeting' },
    ] },
    join: { kicker: 'Join & support', title: 'Stronger together at every ghat.', text: 'Any person in Purba Medinipur whose household depends on fishing or fish work can become a member. Membership is ₹50 per family per year.', steps: pad([
      { title: 'Talk to your village samiti', text: 'Or call the district office. A block coordinator will visit you.' },
      { title: 'Bring your documents', text: 'Aadhaar or voter ID, a passport photo, and your fisher ID card if you have one.' },
      { title: 'Volunteer with us', text: 'Students, doctors, lawyers and teachers can help with camps, legal aid and training.' },
    ], ['1','2','3']) },
    contact: { kicker: 'Contact', title: 'Visit the office', address: ['Jalalkhanbarh (Ward No. 21), Contai Bazar', 'Contai, Purba Medinipur', 'West Bengal — 721403'], hours: 'pmmf2018@yahoo.com', email: 'pmmf2018@yahoo.com', phoneLabel: 'Phone', office: 'PMMF Office', phone: '0000000000', followLabel: 'Follow', social: ['Facebook — PMMF'], facebook: 'https://www.facebook.com/profile.php?id=100068491916726' },
    simple: {
      board: { title: 'Today at the ghat', seaLabel: 'Sea signal', sea: 'Sea is calm — safe to fish', banLabel: 'Fishing ban begins', ban: '15 April', meetLabel: 'Next meeting', meet: '18 Oct · Ramnagar-II' },
      need: 'What do you need?', hint: 'Tap a box to see what to do', stepsLabel: 'What to do', call: 'Call PMMF', whatsapp: 'WhatsApp us', close: 'Close', fight: 'We are fighting for', leadersTitle: 'Your leaders', photosTitle: 'Our coast, our people',
      tiles: [
        { key: 'id', title: 'Fisher ID card', short: 'Apply or renew your card', steps: ['Bring Aadhaar, one photo and your boat or work details.', 'Come to the block camp or the PMMF office.', 'We fill the form with you and follow it up.'] },
        { key: 'ban', title: 'Ban compensation', short: 'Money during the fishing ban', steps: ['Keep your fisher ID card and bank passbook ready.', 'Give your name to your village samiti before 31 March.', 'If payment is late, we take it up with the Fisheries office.'] },
        { key: 'storm', title: 'Cyclone & sea warning', short: 'Stay safe at sea', steps: ['Listen to the village volunteer and radio warnings.', 'Do not go to sea when the red signal is up.', 'Call us at once if a boat is missing or damaged.'] },
        { key: 'trawler', title: 'Report a trawler', short: 'Trawler inside 8 km?', steps: ['Note the boat name or number, the time and the place.', 'Take a photo only if it is safe.', 'Call or WhatsApp the PMMF office.'] },
        { key: 'insure', title: 'Insurance & pension', short: 'Accident cover, old-age pension', steps: ['Ask your village samiti for the form.', 'Bring Aadhaar, bank passbook and fisher ID card.', 'We check your papers and submit them for you.'] },
        { key: 'join', title: 'Join PMMF', short: '₹50 per family per year', steps: ['Talk to your village samiti or call the office.', 'Bring Aadhaar or voter ID and one photo.', 'Get your member card and join your village meeting.'] },
      ],
    },
    theme: {
      chart: { title: 'The 8 km line', text: 'Within 8 km of the shore, the sea is reserved for small traditional boats. When trawlers cross this line they sweep away our nets, our catch and our children’s meals. Protecting this line is protecting our lives.', shore: 'Shore · fishing villages', small: 'Traditional fishing zone', smallRange: '0 – 8 km', trawl: 'Mechanised trawlers', trawlRange: 'beyond 8 km', line: 'No-trawl line · 8 km', harbours: 'Our harbours', legend: 'Chart legend', sheet: 'Sheet', depth: 'Soundings' },
      harbours: [ { name: 'Digha Mohana', coord: '21°38′N 87°30′E' }, { name: 'Shankarpur', coord: '21°38′N 87°34′E' }, { name: 'Junput', coord: '21°43′N 87°49′E' }, { name: 'Petuaghat', coord: '21°47′N 87°53′E' }, { name: 'Khejuri', coord: '21°54′N 87°55′E' } ],
      net: { title: 'One net. Thousands of knots.', text: 'A net holds only because every knot holds. PMMF ties fishers of the sea, the rivers and the ponds together — when one is pulled, all of us feel it.', legend: 'Each knot = 10 women members' },
      boat: { title: 'Every boat carries a village.', text: 'Behind each boat that goes to sea are the women who dry the fish, the vendors who carry it to market, and the children waiting on the shore.' },
      wall: { slogans: ['Fishers’ rights are human rights', 'Save the coast, save the fisherfolk', 'Compensation before the ban!'], sign: '— Purba Medinipur Matsyajibi Forum' },
      ledger: { cover: 'Account book of the fisherfolk', title: 'The ledger of what is owed', text: 'For generations fishers have fed Bengal. This is the account of what is still owed to them.', colNo: 'No.', colOwed: 'What is owed', colBy: 'Owed by', colStatus: 'Status', by: ['State Fisheries Dept.', 'Coast Guard & Fisheries Dept.', 'State Fisheries Dept.', 'District Administration', 'Disaster Management Dept.'], status: ['Pending', 'Pending', 'Partly met', 'Pending', 'Partly met'], totals: 'Our strength, in numbers', signed: 'Signed' },
    },
    footer: '© 2026 Purba Medinipur Matsyajibi Forum · Branch of Dakshinbanga Matsyajibi Forum',
  };

  const bn = {
    langCode: 'bn', otherLang: 'English', img, credit, knots,
    nav: { about: 'আমাদের কথা', work: 'আমাদের কাজ', campaigns: 'আন্দোলন', leadership: 'নেতৃত্ব', news: 'খবর', contact: 'যোগাযোগ', join: 'সদস্য হোন' },
    org: { name: 'পূর্ব মেদিনীপুর মৎস্যজীবী ফোরাম', short: 'পিএমএমএফ', branch: 'দক্ষিণবঙ্গ মৎস্যজীবী ফোরামের (ডিএমএফ) শাখা', since: '২০১৮ থেকে · উপকূলীয় বাংলা' },
    hero: { title: 'সমুদ্র, নদী আর মাছ ধরার অধিকার।', sub: 'পিএমএমএফ ক্ষুদ্র ও ঐতিহ্যবাহী মৎস্যজীবীদের একটি জেলা স্তরের সংগঠন। আমাদের সদস্যরা সরাসরি মৎস্যক্ষেত্রে কাজ করেন, আর আমাদের উদ্দেশ্য মৎস্যজীবীদের সংগঠিত করা, তাঁদের প্রতিনিধিত্ব করা এবং তাঁদের অধিকারের জন্য লড়াই করা।', cta1: 'সদস্য হোন', cta2: 'আমাদের দাবিসমূহ' },
    stats: [
      { value: '১,২০৮', label: 'মহিলা সদস্য' }, { value: '১৮৬', label: 'গ্রাম' },
      { value: '১৫', label: 'ব্লক' }, { value: '২৮০', label: 'নৌকা' },
      { value: '৩', label: 'ক্ষেত্র: সামুদ্রিক, নদী, অভ্যন্তরীণ' }, { value: '২০১৮', label: 'প্রতিষ্ঠার বছর' },
    ],
    about: {
      kicker: 'ফোরাম সম্পর্কে', title: 'মৎস্যজীবীদের জেলা ফোরাম, মৎস্যজীবীদের দ্বারাই পরিচালিত।',
      p1: 'পূর্ব মেদিনীপুরে তিনটি মৎস্যক্ষেত্র আছে: সামুদ্রিক, নদী ও মাছচাষ। জেলার সব ক্ষুদ্র ও ঐতিহ্যবাহী মৎস্যজীবীর প্রতিনিধিত্ব করতে ২০১৮ সালে পিএমএমএফ গঠিত হয় — জলাশয় ও মাছের সম্পদের অবক্ষয়, মাছ ধরার এলাকা থেকে উচ্ছেদ এবং তার ফলে জীবিকা হারানোর মতো সাধারণ সমস্যার মোকাবিলা করতে।',
      p2: 'আমাদের সদস্যরা সামুদ্রিক, নদী ও অভ্যন্তরীণ ক্ষেত্রের মৎস্যজীবী: নৌকার মালিক, নৌকার শ্রমিক ও নৌকা নির্মাতা; মাছ প্রক্রিয়াকরণ, বাছাই, শুকানো ও বিক্রির কাজে যুক্ত মানুষ, যাঁদের বেশিরভাগই মহিলা; এবং অভ্যন্তরীণ ক্ষেত্রে মাছচাষি ও যাঁরা পোনা সরবরাহ, মাছ তোলা, খাবার তৈরি ও পুকুর রক্ষণাবেক্ষণ করেন।',
      members: ['নৌকার মালিক ও শ্রমিক', 'নৌকা নির্মাতা', 'মাছ প্রক্রিয়াকরণ ও শুঁটকি', 'মাছ বিক্রেতা', 'মাছচাষি', 'পোনা সরবরাহ ও পুকুরের কাজ'],
    },
    vision: { label: 'লক্ষ্য', text: 'ক্ষুদ্র মৎস্যজীবীরা যেন এই ক্ষেত্রে কাজ চালিয়ে যেতে পারেন — নিরাপদ জীবিকা, মাছের সম্পদের উপর নিয়ন্ত্রণ, এবং টেকসই পদ্ধতিতে জলাশয় ও মাছ রক্ষার সামর্থ্য নিয়ে।' },
    mission: { label: 'উদ্দেশ্য', text: 'সদস্যভিত্তিক, গণতান্ত্রিক প্রতিনিধিত্ব ও সিদ্ধান্ত গ্রহণের নীতিতে চলা একটি সংগঠন গড়ে তোলা, এবং সদস্যদের সমবেত শক্তিতে মৎস্যজীবীদের দাবি সরকারের সামনে তুলে ধরে তাঁদের সাংবিধানিক অধিকার আদায় করা।' },
    networks: { label: 'সংযুক্ত সংগঠন', items: ['দক্ষিণবঙ্গ মৎস্যজীবী ফোরাম (ডিএমএফ)', 'ন্যাশনাল ফিশওয়ার্কার্স ফোরাম (এনএফএফ)'] },
    history: { kicker: 'আমাদের পথচলা', title: 'গুরুত্বপূর্ণ মুহূর্ত', items: [
      { year: '২০১৬', title: 'দুর্নীতি-বিরোধী অভিযান', text: 'সরকারি নৌকা-নির্মাণ প্রকল্পে দুর্নীতির বিরুদ্ধে অভিযান শুরু।' },
      { year: '২০১৮', title: 'বগুড়ান জালপাই সৈকত রক্ষা', text: 'সৈকতে গাড়ি চলাচল নিয়ন্ত্রণের লড়াইয়ে জয়; পরে সরকার সৈকতটিকে জীববৈচিত্র্য ঐতিহ্য স্থল ঘোষণা করে।' },
      { year: '২০১৯', title: 'সিআরজেড আন্দোলন শুরু', text: 'উপকূল সুরক্ষা আইন শিথিল করার বিরুদ্ধে কোস্টাল রেগুলেশন জোন আন্দোলন শুরু।' },
      { year: '২০২১', title: 'ইয়াস ঘূর্ণিঝড়', text: 'ঘূর্ণিঝড়ের পর জীবিকার ত্রাণ ও ক্ষতিপূরণের জন্য লড়াই।' },
      { year: '২০২২', title: 'বাসস্থানের অধিকার অর্জন', text: 'উপকূলের কাছে মৎস্যজীবীদের ঘর তৈরির আইনি অধিকার আদায়।' },
      { year: '২০২২', title: 'নদীতে নৌকা নিবন্ধন', text: 'নৌকা নিবন্ধন প্রকল্প অভ্যন্তরীণ নদী ক্ষেত্রে সম্প্রসারণের নীতি পরিবর্তন।' },
      { year: '২০২৩', title: 'মাছ ঘাটের স্বীকৃতি', text: 'সমষ্টিগত মাছ নামানোর ঘাট চিহ্নিত করে মৎস্য দপ্তরের নীতিতে অন্তর্ভুক্তি।' },
      { year: '২০২৫', title: 'মহিলা শাখা গঠন', text: 'সংগঠনের নিজস্ব মহিলা শাখা গঠিত হয়।' },
      { year: '২০২৫', title: 'উপকূলীয় পদযাত্রা', text: '“জল বাঁচাও, উপকূল বাঁচাও, মৎস্যজীবী বাঁচাও” ব্যানারে উপকূল জুড়ে পদযাত্রা।' },
      { year: '২০২৬', title: 'দেরেদিঘি খাল সাফাই', text: 'ভগবানপুর-১ ব্লকের মারাত্মক দূষিত দেরেদিঘি খাল পরিষ্কার।' },
    ] },
    work: { kicker: 'আমাদের কাজের ক্ষেত্র', title: 'নৌকা থেকে বাজার — প্রতিটি অধিকারের লড়াই।', items: pad([
      { title: 'জীবিকার অধিকার ও মাছ ধরার এলাকা', text: 'ঐতিহ্যবাহী মাছ ধরার এলাকা ও সেখানে মাছ ধরার অধিকার রক্ষা।' },
      { title: 'টেকসই মৎস্যচর্চা', text: 'ধ্বংসাত্মক বটম ট্রলিং নিষিদ্ধ করার দাবি।' },
      { title: 'নিবিড় চিংড়ি চাষের বিরুদ্ধে', text: 'বিকল্প, টেকসই মাছচাষের মডেল তুলে ধরা।' },
      { title: 'পরিচয়পত্র ও সরকারি প্রকল্প', text: 'মৎস্যজীবী পরিচয়পত্র, নিবন্ধন ও সরকারি প্রকল্পের সুবিধা।' },
      { title: 'নিষেধাজ্ঞার ক্ষতিপূরণ', text: 'বার্ষিক মাছ ধরা নিষেধাজ্ঞার সময় জীবিকা হারানোর ক্ষতিপূরণ।' },
      { title: 'ঘূর্ণিঝড় প্রস্তুতি ও ত্রাণ', text: 'ঘূর্ণিঝড়ের আগে প্রস্তুতি, পরে ত্রাণ ও পুনর্বাসন।' },
      { title: 'সমুদ্রে নিরাপত্তা', text: 'নিরাপদ নৌকা, সরঞ্জাম ও উদ্ধার ব্যবস্থা।' },
      { title: 'সামাজিক সুরক্ষা', text: 'বিমা, পেনশন ও কল্যাণ প্রকল্প।' },
      { title: 'সীমান্তে আটক মৎস্যজীবী', text: 'সমুদ্রসীমা পেরিয়ে আটক মৎস্যজীবীদের পাশে থাকা।' },
      { title: 'সিআরজেড, জমি ও বাসস্থান', text: 'উপকূল নিয়ন্ত্রণ, জমির অধিকার ও বসতি উচ্ছেদের বিরুদ্ধে লড়াই।' },
      { title: 'পর্যটন, বন্দর ও শিল্প', text: 'পর্যটন, জাহাজ চলাচল, ড্রেজিং, বন্দর ও শিল্প প্রকল্পের সঙ্গে সংঘাত।' },
      { title: 'ম্যানগ্রোভ ও উপকূল রক্ষা', text: 'ম্যানগ্রোভ ও উপকূল সংরক্ষণ।' },
      { title: 'মৎস্যক্ষেত্রে মহিলা', text: 'শুঁটকি, প্রক্রিয়াকরণ, বাজার ও ঋণ — মহিলা মৎস্যজীবীদের জন্য।' },
      { title: 'ন্যায্য দাম ও বাজার', text: 'ন্যায্য দাম, বাজারে প্রবেশ ও ঋণের জাল থেকে মুক্তি।' },
      { title: 'শিক্ষা ও স্বাস্থ্য', text: 'মৎস্যজীবী গ্রামে শিক্ষা ও স্বাস্থ্য।' },
      { title: 'আইনি সহায়তা ও অধিকার সচেতনতা', text: 'আইনি সাহায্য ও মৎস্যজীবীদের অধিকার সম্পর্কে সচেতনতা।' },
      { title: 'প্রশিক্ষণ ও যুব নেতৃত্ব', text: 'প্রশিক্ষণ কর্মসূচি ও তরুণ নেতৃত্ব গড়ে তোলা।' },
      { title: 'দূষণ', text: 'শিল্পবর্জ্য, প্লাস্টিক দূষণ ও নিকাশি নিঃসরণের বিরুদ্ধে পদক্ষেপ।' },
    ], bnNum) },
    campaigns: { kicker: 'চলমান আন্দোলন', title: 'আজ আমাদের দাবি', addressed: 'দাবিগুলি জানানো হয়েছে পশ্চিমবঙ্গ সরকারের মৎস্য দপ্তর, পূর্ব মেদিনীপুরের জেলাশাসক এবং ভারত সরকারের মৎস্য বিভাগকে।', items: pad([
      { text: 'মাছ ধরা নিষেধাজ্ঞার ক্ষতিপূরণ বাড়াতে হবে এবং নিষেধাজ্ঞা শুরুর আগেই দিতে হবে।' },
      { text: 'ঐতিহ্যবাহী মৎস্যজীবীদের জন্য সংরক্ষিত ৮ কিমি ট্রলার-নিষিদ্ধ এলাকা কঠোরভাবে বলবৎ করতে হবে।' },
      { text: 'মহিলা শুঁটকি শ্রমিক সহ প্রত্যেক মৎস্যজীবীকে পরিচয়পত্র দিতে হবে।' },
      { text: 'মৎস্যজীবী বসতি উচ্ছেদ চলবে না; উপকূল পরিকল্পনায় প্রথাগত অধিকার নথিভুক্ত করতে হবে।' },
      { text: 'প্রতিটি কেন্দ্রে উদ্ধারকারী নৌকা, রেডিও ও ঘূর্ণিঝড় আশ্রয়কেন্দ্র চাই।' },
    ], bnNum) },
    leaders: { kicker: 'নেতৃত্ব', title: 'পদাধিকারীগণ', photo: 'ছবি', items: withIds([
      { name: 'অমল ভূঁইয়া', role: 'সভাপতি', place: 'মহিষাদল ব্লক' },
      { name: 'শ্রীকান্ত দাস', role: 'সহ-সভাপতি', place: 'রামনগর-২ ব্লক' },
      { name: 'দেবাশিস শ্যামল', role: 'সম্পাদক', place: 'কাঁথি-১ ব্লক' },
      { name: 'সাহিদা বিবি', role: 'সহ-সম্পাদক', place: 'নন্দীগ্রাম-১ ব্লক' },
      { name: 'রবীন্দ্রনাথ ভূঁইয়া', role: 'কোষাধ্যক্ষ', place: 'কাঁথি-১ ব্লক' },
    ]),
      structureTitle: 'ফোরামের গঠন', structureText: 'সাধারণ সভা বছরে একবার · কার্যনির্বাহী কমিটি প্রতি মাসে · ব্লক ইউনিট দুই মাস অন্তর · গ্রাম সমিতি প্রতি মাসে।',
      womenTitle: 'মহিলা শাখা', womenText: 'মহিলা শাখা শুঁটকি শ্রমিক ও মাছ বিক্রেতাদের সংগঠিত করে। কার্যনির্বাহী কমিটির এক-তৃতীয়াংশ আসন মহিলাদের জন্য সংরক্ষিত।' },
    news: { kicker: 'খবর ও অনুষ্ঠান', title: 'উপকূল থেকে', upcomingLabel: 'আসন্ন', items: withNews([
      { date: '১২ সেপ্টেম্বর ২০২৬', title: 'নিষেধাজ্ঞার ক্ষতিপূরণ নিয়ে জেলাশাসকের কাছে ডেপুটেশন', text: '৩০০-র বেশি মৎস্যজীবী তমলুকে মিছিল করে সময়মতো ভাতার দাবি জানান।' },
      { date: '২৮ আগস্ট ২০২৬', title: 'পেটুয়াঘাটে লাইফ জ্যাকেট বিতরণ', text: 'পেটুয়াঘাট ও শংকরপুরে ছোট নৌকার শ্রমিকদের ৪০০টি লাইফ জ্যাকেট দেওয়া হয়।' },
      { date: '৫ আগস্ট ২০২৬', title: 'খেজুরি-২-এ পরিচয়পত্র শিবির', text: '৬০০-র বেশি মৎস্যজীবী, যাঁদের এক-তৃতীয়াংশ মহিলা, পরিচয়পত্রের আবেদন করেন।' },
      { date: '২১ জুলাই ২০২৬', title: 'জুনপুটে মহিলা শুঁটকি শ্রমিকদের সভা', text: 'শুকানোর জায়গা, ন্যায্য ঋণ ও যৌথ বাজার-স্টল নিয়ে আলোচনা।' },
      { date: '৩০ জুন ২০২৬', title: 'রসুলপুরে ম্যানগ্রোভ চারা রোপণ', text: 'গ্রাম সমিতিগুলি ৫,০০০ চারা রোপণ করে রক্ষী দল গঠন করে।' },
    ]), upcoming: [
      { date: '১৮ অক্টোবর ২০২৬', text: 'ব্লক সম্মেলন, রামনগর-২' },
      { date: '২১ নভেম্বর ২০২৬', text: 'বিশ্ব মৎস্য দিবসের মিছিল, কাঁথি' },
      { date: 'ডিসেম্বর ২০২৬', text: 'বার্ষিক সাধারণ সভা' },
    ] },
    join: { kicker: 'যোগ দিন ও পাশে থাকুন', title: 'প্রতিটি ঘাটে, একসাথে আরও শক্তিশালী।', text: 'পূর্ব মেদিনীপুরের যে কোনও ব্যক্তি, যাঁর পরিবার মাছ ধরা বা মাছের কাজের উপর নির্ভরশীল, সদস্য হতে পারেন। সদস্য চাঁদা পরিবার প্রতি বছরে ₹৫০।', steps: pad([
      { title: 'গ্রাম সমিতির সঙ্গে কথা বলুন', text: 'অথবা জেলা অফিসে ফোন করুন। ব্লক সংগঠক আপনার কাছে আসবেন।' },
      { title: 'নথিপত্র আনুন', text: 'আধার বা ভোটার কার্ড, পাসপোর্ট ছবি এবং মৎস্যজীবী পরিচয়পত্র (যদি থাকে)।' },
      { title: 'স্বেচ্ছাসেবক হোন', text: 'ছাত্র, ডাক্তার, আইনজীবী ও শিক্ষকরা শিবির, আইনি সহায়তা ও প্রশিক্ষণে সাহায্য করতে পারেন।' },
    ], ['১','২','৩']) },
    contact: { kicker: 'যোগাযোগ', title: 'অফিসে আসুন', address: ['জালালখানবাড় (ওয়ার্ড নং ২১), কাঁথি বাজার', 'কাঁথি, পূর্ব মেদিনীপুর', 'পশ্চিমবঙ্গ — ৭২১৪০৩'], hours: 'pmmf2018@yahoo.com', email: 'pmmf2018@yahoo.com', phoneLabel: 'ফোন', office: 'পিএমএমএফ অফিস', phone: '0000000000', followLabel: 'আমাদের অনুসরণ করুন', social: ['ফেসবুক — পিএমএমএফ'], facebook: 'https://www.facebook.com/profile.php?id=100068491916726' },
    simple: {
      board: { title: 'আজ ঘাটে', seaLabel: 'সমুদ্র সংকেত', sea: 'সমুদ্র শান্ত — মাছ ধরা যাবে', banLabel: 'মাছ ধরা নিষেধাজ্ঞা শুরু', ban: '১৫ এপ্রিল', meetLabel: 'পরের সভা', meet: '১৮ অক্টোবর · রামনগর-২' },
      need: 'আপনার কী দরকার?', hint: 'কী করতে হবে জানতে বাক্সে চাপ দিন', stepsLabel: 'কী করবেন', call: 'পিএমএমএফ-কে ফোন করুন', whatsapp: 'হোয়াটসঅ্যাপ করুন', close: 'বন্ধ করুন', fight: 'আমরা লড়ছি যার জন্য', leadersTitle: 'আপনার নেতৃত্ব', photosTitle: 'আমাদের উপকূল, আমাদের মানুষ',
      tiles: [
        { key: 'id', title: 'মৎস্যজীবী পরিচয়পত্র', short: 'নতুন কার্ড বা নবীকরণ', steps: ['আধার, একটি ছবি আর নৌকা বা কাজের তথ্য আনুন।', 'ব্লকের শিবিরে বা পিএমএমএফ অফিসে আসুন।', 'আমরা আপনার সঙ্গে ফর্ম ভরে পিছনে লেগে থাকব।'] },
        { key: 'ban', title: 'নিষেধাজ্ঞার ক্ষতিপূরণ', short: 'মাছ ধরা বন্ধের সময়ের টাকা', steps: ['মৎস্যজীবী পরিচয়পত্র ও ব্যাংকের পাসবই তৈরি রাখুন।', '৩১ মার্চের আগে গ্রাম সমিতিতে নাম দিন।', 'টাকা দেরি হলে আমরা মৎস্য দপ্তরে কথা বলব।'] },
        { key: 'storm', title: 'ঘূর্ণিঝড় ও সমুদ্র সতর্কতা', short: 'সমুদ্রে নিরাপদ থাকুন', steps: ['গ্রামের স্বেচ্ছাসেবক ও রেডিওর সতর্কবার্তা শুনুন।', 'লাল সংকেত থাকলে সমুদ্রে যাবেন না।', 'নৌকা নিখোঁজ বা ক্ষতিগ্রস্ত হলে সঙ্গে সঙ্গে ফোন করুন।'] },
        { key: 'trawler', title: 'ট্রলারের খবর দিন', short: '৮ কিমি-র মধ্যে ট্রলার?', steps: ['নৌকার নাম বা নম্বর, সময় ও জায়গা লিখে রাখুন।', 'নিরাপদ হলে তবেই ছবি তুলুন।', 'পিএমএমএফ অফিসে ফোন বা হোয়াটসঅ্যাপ করুন।'] },
        { key: 'insure', title: 'বিমা ও পেনশন', short: 'দুর্ঘটনা বিমা, বার্ধক্য ভাতা', steps: ['গ্রাম সমিতির কাছে ফর্ম চেয়ে নিন।', 'আধার, ব্যাংকের পাসবই ও পরিচয়পত্র আনুন।', 'আমরা কাগজ দেখে জমা করে দেব।'] },
        { key: 'join', title: 'পিএমএমএফ-এ যোগ দিন', short: 'পরিবার প্রতি বছরে ₹৫০', steps: ['গ্রাম সমিতির সঙ্গে কথা বলুন বা অফিসে ফোন করুন।', 'আধার বা ভোটার কার্ড ও একটি ছবি আনুন।', 'সদস্য কার্ড নিন ও গ্রামের সভায় যোগ দিন।'] },
      ],
    },
    theme: {
      chart: { title: '৮ কিমি রেখা', text: 'উপকূল থেকে ৮ কিমি পর্যন্ত সমুদ্র ছোট ঐতিহ্যবাহী নৌকার জন্য সংরক্ষিত। ট্রলার এই রেখা পেরোলে ভেসে যায় আমাদের জাল, মাছ আর সন্তানদের মুখের ভাত। এই রেখা রক্ষা মানে আমাদের জীবন রক্ষা।', shore: 'উপকূল · মৎস্যজীবী গ্রাম', small: 'ঐতিহ্যবাহী মাছ ধরার এলাকা', smallRange: '০ – ৮ কিমি', trawl: 'যন্ত্রচালিত ট্রলার', trawlRange: '৮ কিমি-র বাইরে', line: 'ট্রলার-নিষিদ্ধ রেখা · ৮ কিমি', harbours: 'আমাদের বন্দর', legend: 'মানচিত্র সংকেত', sheet: 'পাতা', depth: 'গভীরতা' },
      harbours: [ { name: 'দিঘা মোহনা', coord: '২১°৩৮′উ ৮৭°৩০′পূ' }, { name: 'শংকরপুর', coord: '২১°৩৮′উ ৮৭°৩৪′পূ' }, { name: 'জুনপুট', coord: '২১°৪৩′উ ৮৭°৪৯′পূ' }, { name: 'পেটুয়াঘাট', coord: '২১°৪৭′উ ৮৭°৫৩′পূ' }, { name: 'খেজুরি', coord: '২১°৫৪′উ ৮৭°৫৫′পূ' } ],
      net: { title: 'একটি জাল, হাজার গিঁট।', text: 'প্রতিটি গিঁট শক্ত বলেই জাল টেকে। পিএমএমএফ সমুদ্র, নদী ও পুকুরের মৎস্যজীবীদের এক বাঁধনে বাঁধে — একজনকে টান দিলে আমরা সবাই টের পাই।', legend: 'প্রতিটি গিঁট = ১০ জন মহিলা সদস্য' },
      boat: { title: 'প্রতিটি নৌকায় ভাসে একটা গোটা গ্রাম।', text: 'সমুদ্রে যাওয়া প্রতিটি নৌকার পিছনে আছেন শুঁটকি শুকানো মহিলারা, বাজারে মাছ নিয়ে যাওয়া বিক্রেতারা, আর তীরে অপেক্ষারত শিশুরা।' },
      wall: { slogans: ['মৎস্যজীবীর অধিকার মানবাধিকার', 'উপকূল বাঁচাও, মৎস্যজীবী বাঁচাও', 'নিষেধাজ্ঞার আগেই ক্ষতিপূরণ চাই!'], sign: '— পূর্ব মেদিনীপুর মৎস্যজীবী ফোরাম' },
      ledger: { cover: 'মৎস্যজীবীদের হিসাবের খাতা', title: 'প্রাপ্য হিসাবের খাতা', text: 'প্রজন্মের পর প্রজন্ম মৎস্যজীবীরা বাংলার মুখে খাবার তুলে দিয়েছেন। এ খাতা তাঁদের এখনও প্রাপ্য বাকির হিসাব।', colNo: 'ক্রম', colOwed: 'প্রাপ্য', colBy: 'দায়', colStatus: 'অবস্থা', by: ['রাজ্য মৎস্য দপ্তর', 'উপকূল রক্ষী ও মৎস্য দপ্তর', 'রাজ্য মৎস্য দপ্তর', 'জেলা প্রশাসন', 'বিপর্যয় মোকাবিলা দপ্তর'], status: ['বাকি', 'বাকি', 'আংশিক', 'বাকি', 'আংশিক'], totals: 'সংখ্যায় আমাদের শক্তি', signed: 'স্বাক্ষর' },
    },
    footer: '© ২০২৬ পূর্ব মেদিনীপুর মৎস্যজীবী ফোরাম · দক্ষিণবঙ্গ মৎস্যজীবী ফোরামের শাখা',
  };

  window.PMMF = { en, bn };
})();
